hmpps-auth:
  url: "${HMPPS_AUTH_URL:http://localhost:8090/auth}"

api:
  client:
    id: "${API_CLIENT_ID}"
    secret: "${API_CLIENT_SECRET}"

hmpps-prisoner-search-api:
  url: "${HMPPS_PRISONER_SEARCH_API_URL:http://localhost:8080}"

hmpps-prison-api:
  url: "${HMPPS_PRISON_API_URL:http://localhost:8080}"

spring:
  config:
    import: optional:file:.env.dev[.properties]
  datasource:
    url: 'jdbc:postgresql://${DB_SERVER}/${DB_NAME}'
