hmpps-auth:
  url: "${HMPPS_AUTH_URL:http://localhost:8090/auth}"

api:
  client:
    id: "example-api-client"
    secret: "example-api-client-secret"

hmpps-prisoner-search-api:
  url: "http://localhost:8080"

hmpps-prison-api:
  url: "http://localhost:8080"

spring:
  config:
    import: optional:file:.env.dev[.properties]
  datasource:
    url: 'jdbc:postgresql://${DB_SERVER}/${DB_NAME}'
