---
# Per environment values which override defaults in hmpps-manage-pom-cases-api/values.yaml

generic-service:
  ingress:
    host: manage-pom-cases-api-dev.prison.service.justice.gov.uk

  env:
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: "applicationinsights.dev.json"
    HMPPS_AUTH_URL: "https://sign-in-dev.hmpps.service.justice.gov.uk/auth"
    HMPPS_PRISONER_SEARCH_API_URL: "https://prisoner-search-dev.prison.service.justice.gov.uk"
    HMPPS_PRISON_API_URL: "https://prison-api-dev.prison.service.justice.gov.uk"

# CloudPlatform AlertManager receiver to route prometheus alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  alertSeverity: mpc-alerts-nonprod-dev
  businessHoursOnly: true
  rdsAlertsDatabases:
    cloud-platform-41002da28ca693e2: dev
